sudo: false

language: go

go:
  - 1.6

branches:
  only:
    - master

before_script: |-
  wget -O consul.zip -q https://releases.hashicorp.com/consul/0.7.0/consul_0.7.0_linux_amd64.zip
  unzip consul.zip
  mkdir -p ~/bin
  mv consul ~/bin/

script: make test

notifications:
  email: false
